**Rad sa matricama**
- numpy biblioteka

In [2]:
import numpy as np

In [5]:
# jednodimenzioni niz
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [6]:
# matrica
M = np.array([[1, 2, 3], [4, 5, 6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# dimenzija matrice
M.shape

(2, 3)

In [8]:
x.shape

(3,)

In [11]:
# promena dimenzije
x = x.reshape(1, 3)
x.shape

(1, 3)

In [12]:
x

array([[1, 2, 3]])

In [13]:
M.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
M.reshape(1, 6)
# nije moguce M.reshape(1, 5)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
# interval
list(range(2, 5))

[2, 3, 4]

In [18]:
np.arange(2, 5)

array([2, 3, 4])

In [19]:
# interval sa korakom
np.arange(2, 10, 3)

array([2, 5, 8])

In [21]:
# niz elemenata koji su ravnomerno rasporedjeni
np.linspace(1, 10, 21)

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [22]:
# matric/niz nula
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# matrica/niz jedinica
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# jedinicna matrica
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# vektor
y = np.array([1, 2, 4])

In [26]:
# diagonalna matrica od vektora
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [27]:
# random - standardna normalna raspodela
np.random.randn(2, 3)

array([[ 0.0219153 , -2.25911314, -0.86012414],
       [ 0.06702301,  0.18233769, -2.25843566]])

**Operacije sa matricama**

In [29]:
M1 = np.array([[10, 2, 31], [4, 45, 6], [1, 2, 3]])
M2 = np.array([[0, 1, 2], [4, 5, 6], [7, 8, 9]])

In [30]:
M1

array([[10,  2, 31],
       [ 4, 45,  6],
       [ 1,  2,  3]])

In [31]:
M2

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# sabiranje (sabira po koordinatama)
M1 + M2

array([[10,  3, 33],
       [ 8, 50, 12],
       [ 8, 10, 12]])

In [33]:
# mnozenje (po koordinatama)
M1 * M2

array([[  0,   2,  62],
       [ 16, 225,  36],
       [  7,  16,  27]])

In [34]:
# mnozenje matrica
M1.dot(M2)

array([[225, 268, 311],
       [222, 277, 332],
       [ 29,  35,  41]])

In [35]:
# transponovana matrica
M1.transpose()

array([[10,  4,  1],
       [ 2, 45,  2],
       [31,  6,  3]])

In [36]:
# ili
M1.T

array([[10,  4,  1],
       [ 2, 45,  2],
       [31,  6,  3]])

In [37]:
# primena f-je (po koordinatama)
np.sin(M1)

array([[-0.54402111,  0.90929743, -0.40403765],
       [-0.7568025 ,  0.85090352, -0.2794155 ],
       [ 0.84147098,  0.90929743,  0.14112001]])

In [38]:
M1[M1>10]

array([31, 45])

In [39]:
# poredjenje (po koordinatama)
M1 == M2

array([[False, False, False],
       [ True, False,  True],
       [False, False, False]])

In [43]:
# sabiranje skalarom (po koordinatama)
M1 + 2

array([[12,  4, 33],
       [ 6, 47,  8],
       [ 3,  4,  5]])

In [40]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [41]:
# vertikalno nadovezivanje
np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# horizontalno nadovezivanje
np.hstack((x, y))

array([1, 2, 3, 4, 5, 6])

In [44]:
# svaki red matrice se sabira sa vektorom
M1 + x

array([[11,  4, 34],
       [ 5, 47,  9],
       [ 2,  4,  6]])

In [45]:
# mnozenje skalarom po koordinatama
3 * M

array([[ 3,  6,  9],
       [12, 15, 18]])

In [46]:
# izdvajanje druge kolone
M1[:,1]

array([ 2, 45,  2])

In [47]:
# izdvajanje druge vrste
M1[1,:]

array([ 4, 45,  6])

In [48]:
M1[1, 1:2]

array([45])

In [50]:
E = np.eye(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
# izdvajanje poslednje kolone
E[:, -1]

array([0., 0., 0., 0., 1.])

In [53]:
# izdvajanje sa korakom -1 
E[:,::-1]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [54]:
E[-1, ::-1]

array([1., 0., 0., 0., 0.])