In [4]:
import numpy as np

In [5]:
from numpy import linalg as LA

In [9]:
M1 = np.array([[10, 2, 31], [4, 45, 6], [1, 2, 3]])

In [10]:
# determinanta matrice
LA.det(M1)

71.0

In [11]:
# inverz matrice
LA.inv(M1)

array([[ 1.73239437e+00,  7.88732394e-01, -1.94788732e+01],
       [-8.45070423e-02, -1.40845070e-02,  9.01408451e-01],
       [-5.21126761e-01, -2.53521127e-01,  6.22535211e+00]])

In [12]:
# jedinicna matrica
LA.inv(M1).dot(M1)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [13]:
# sopstvene vrednosti i vektori
LA.eig(M1)

(array([45.68993567, 12.18250827,  0.12755606]),
 array([[-0.09814506, -0.98779287, -0.95272431],
        [-0.99397166,  0.1347019 ,  0.04474363],
        [-0.04886605, -0.07823451,  0.30052355]]))

In [14]:
eig_vals, eig_vecs = LA.eig(M1)

In [15]:
eig_vals

array([45.68993567, 12.18250827,  0.12755606])

In [16]:
eig_vecs

array([[-0.09814506, -0.98779287, -0.95272431],
       [-0.99397166,  0.1347019 ,  0.04474363],
       [-0.04886605, -0.07823451,  0.30052355]])

In [17]:
# vektor
x = np.array([1, 2, 3])

In [18]:
# norma vektora
LA.norm(x)

3.7416573867739413

In [19]:
LA.norm(x, ord=2)

3.7416573867739413

In [20]:
# norma matrice
LA.norm(M1, ord=2)

46.650646365483155

In [21]:
LA.norm(M1, ord='fro')

56.178287620752556

In [22]:
# uslovljenost matrice
LA.cond(M1, p='fro')

1155.3628922615267

In [23]:
LA.norm(M1) * LA.norm(LA.inv(M1))

1155.3628922615267